// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isElectron } from '@/utils/platformUtils';

// Try to get the URL and key from environment variables first, 
// then fall back to global variables set in index.html
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (window as any).SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || (window as any).SUPABASE_ANON_KEY;

// Make sure we have the URL and key
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Silent error handling for production
}

// Create a custom storage implementation that clears on sign out
const customStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key);
    } catch (error) {
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage.setItem(key, value);
    } catch (error) {
      // Silent error handling for production
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
    } catch (error) {
      // Silent error handling for production
    }
  }
};

export const supabase = createClient<Database>(
  SUPABASE_URL as string, 
  SUPABASE_PUBLISHABLE_KEY as string,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: customStorage,
      storageKey: 'call-card-auth',
      detectSessionInUrl: !isElectron(), // Only detect session in URL for web version
      flowType: isElectron() ? 'pkce' : 'implicit' // Use PKCE for Electron, implicit for web
    }
  }
);
